### ISSUE TITLE
Potential Issue

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [robsonde/digitalocean_builder#1]
[Arch linux base group](https://www.archlinux.org/news/base-group-replaced-by-mandatory-base-package-manual-intervention-required/) no longer contains 
* linux kernel 
* linux-firmware (shouldn't be a problem here)
* an editor

You may want to update your install scripts to reflect this
https://github.com/robsonde/digitalocean_builder/blob/ee9f1ea6b737168af102f0f5a7cdf17e669e5b86/make_image.sh#L84

**Comment by robsonde** [comment]
Good spotting.

Should now be fixed, I have added a few packages so you get nano and vi along with the Linux kernel and firmware and basic network stuff.
